import { StyleSheet } from 'react-native';
import { colors } from '@app/styles/colors';

export const s = StyleSheet.create({
  center: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  searchInput: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginBottom: 12,
    backgroundColor: colors.white,
    fontSize: 16,
  },
  tagsRow: { marginBottom: 12, flexGrow: 0 },
  tagsRowContent: { gap: 8, alignItems: 'center' },
  tag: {
    borderWidth: 1,
    borderColor: colors.border,
    paddingVertical: 2,
    paddingHorizontal: 8,
    borderRadius: 12,
    backgroundColor: colors.white,
  },
  tagSelected: { backgroundColor: colors.primary, borderColor: colors.primary, shadowColor: colors.primary, shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.3, shadowRadius: 3, elevation: 2 },
  tagText: { color: colors.primary, fontSize: 12 },
  tagTextSelected: { color: colors.white },
  card: {
    padding: 14,
    borderRadius: 14,
    marginBottom: 10,
    backgroundColor: colors.white,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 3,
  },
  title: { fontWeight: '700', fontSize: 16, marginBottom: 2 },
  ingredientCount: { fontSize: 13, color: colors.muted, marginBottom: 4 },
  source: { color: colors.secondary },
  link: { color: colors.link, textDecorationLine: 'underline' },
  emptyText: { padding: 12, color: colors.muted },
  cardTagsRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 4, marginTop: 6 },
  cardTag: {
    paddingVertical: 2,
    paddingHorizontal: 8,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.ghostBg,
  },
  cardTagText: { fontSize: 11, color: colors.muted },
});
